### PR TITLE
Update file comment header titles

### PR DESCRIPTION
**Pull request by simplyrohan**
Fixes: #2006 

Updates title from old `pygame` title in the codebase to `pygame-ce` in `font.c`.

### CODE REVIEW

**Comment by yunline** [comment]
image
Humm, it seems there are 79 else.

**Comment by MyreMylar** [comment]
@simplyrohan Do you want to fix _all_ of these headers or are you happy stopping here?

Probably we should decide on a standard modern copyright header if we are going to have one and exclude the year. e.g.

```
/*
    pygame-ce - Pygame Community Edition Library
    Copyright (C) The Pygame Community Edition Contributors.

    Based on the Pygame library, originally created by Pete Shinners

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Website: https://pyga.me/
*/

```

**Review by MyreMylar — APPROVED** [review]

**Comment by simplyrohan** [comment]
@novialriptide told me this, and I am making a commit at the moment. I thought the headers had already been changed and we simply forgot this one.

**Review by novialriptide — APPROVED** [review]
LGTM

**Review by MyreMylar — APPROVED** [review]
OK, LGTM 👍

**Pull request merged**
