### PR TITLE
Draw arc test in draw_test.py

### PR DESCRIPTION
**Pull request by Akaracy**
I modified the test test_arc__correct_drawing() in draw_test.py as asked in https://github.com/pygame-community/pygame-ce/issues/2636 and https://github.com/pygame-community/pygame-ce/pull/2638 .
I added a wider range of widths and angles to test the arc function.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for contributing to pygame-ce :partying_face: 
Thanks to the PR of the original author as well!

**Comment by ankith26** [comment]
Requesting Myre's review as they had reviewed the original PR

**Review by bilhox — APPROVED** [review]
LGTM ! Thanks for the contribution 😄 !

**Review by MyreMylar — APPROVED** [review]
LGTM! 👍

**Pull request merged**
