### PR TITLE
wasm: better wasm fencing

### PR DESCRIPTION
**Pull request by pmp-p**

### CODE REVIEW

**Review by damusss — APPROVED** [review]
Makes sense, LGTM :)

**Review by ankith26 — COMMENTED** [review]
A lot of places in the codebase use `__EMSCRIPTEN__` for webasm fencing, what about those usages, should they all be updated to have wasi fencing too?

**Comment by pmp-p** [comment]
each fence need invididual review wasi and web can be very different, in case of timers it was not clear how to make them work BOTH on wasi and web but it may be possible to run them from pump()

Let's assume `defined(__EMSCRIPTEN__) || defined(__wasi__)` means there is a way to do both and just __EMSCRIPTEN__ would mean unknown yet.

**Review by ankith26 — APPROVED** [review]
Okay, LGTM. Thanks! :partying_face:

**Pull request merged**
