### PR TITLE
Update SDL 2.26.5 -> 2.28.5

### PR DESCRIPTION
**Pull request by Starbuck5**
I had been delaying this because I thought it would break any usage of Window, but I think I was wrong on that, given the exact wording here: https://github.com/pygame-community/pygame-ce/issues/2190#issuecomment-1585713685

Also we now have a software rendering window API in, so we're good regardless

Started this under a different PR, https://github.com/pygame-community/pygame-ce/pull/2578, foiled again by the fact that these doc update PRs can't be on fork branches, they need to be on this repo branches.

### CODE REVIEW

**Comment by ankith26** [comment]
My PR #2549 fixes the fail that you are seeing on this branch

**Review by dr0id — APPROVED** [review]
seems to be only version numbers updates... can't say if these are all that need to be updated.

otherwise
LGTM

**Comment by Starbuck5** [comment]
> My PR https://github.com/pygame-community/pygame-ce/pull/2549 fixes the fail that you are seeing on this branch

Now that that is merged, I've rebased this branch to run the CI through again.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Pull request merged**
