### PR TITLE
Update windows deps

### PR DESCRIPTION
**Pull request by Starbuck5**
Tested and validated locally on my Windows system.

### CODE REVIEW

**Review by MyreMylar — APPROVED** [review]
LGTM and works on my windows machine 👍

**Comment by ankith26** [comment]
I'd like to hold this PR till mac/manylinux is updated as well. Which I'd like to tackle soon-ish

**Comment by Starbuck5** [comment]
>  I'd like to hold this PR till mac/manylinux is updated as well. Which I'd like to tackle soon-ish

I was going to request that PR from you, but you're already thinking of it :)

**Comment by oddbookworm** [comment]
Seems fine on Windows 11 from my testing
```
>>> import pygame
pygame-ce 2.2.0.dev1 (SDL 2.26.4, Python 3.11.1)
>>> pygame.init()
(5, 0)
>>> pygame.print_debug_info()
Platform:               Windows-10-10.0.22621-SP0
System:                 Windows
System Version:         10.0.22621
Processor:              AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
Architecture:           Bits: 64bit     Linkage: WindowsPE
Driver:                 windows

Python:                 CPython
pygame version:         2.2.0.dev1
python version:         3.11.1

SDL versions:           Linked: 2.26.4  Compiled: 2.26.4
SDL Mixer versions:     Linked: 2.6.3   Compiled: 2.6.3
SDL Font versions:      Linked: 2.20.2  Compiled: 2.20.2
SDL Image versions:     Linked: 2.0.5   Compiled: 2.0.5
Freetype versions:      Linked: 2.11.1  Compiled: 2.11.1
```

**Review by oddbookworm — APPROVED** [review]

**Pull request merged**
