### PR TITLE
Issue redirection (correct one)

### PR DESCRIPTION
**Pull request by oddbookworm**
Continuation of #2202 so that the manylinux runs can pass

### CODE REVIEW

**Comment by Starbuck5** [comment]
Is it in the scope of this PR to retarget things that aren't full links, but say `issue #xyz`?

For example, https://github.com/pygame-community/pygame-ce/blob/c4095e69f7ce54f85f1b7f93093c6cc9ab9a1221/test/color_test.py#L588

**Comment by oddbookworm** [comment]
> Is it in the scope of this PR to retarget things that aren't full links, but say `issue #xyz`?

I believe it would be. I need to step away for a bit, but I can do a more thorough search for these when I come back

**Comment by oddbookworm** [comment]
I'm pretty sure I got them all

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Review by zoldalma999 — APPROVED** [review]
Thanks!

**Pull request merged**
