### PR TITLE
New up-to-date review of french readme + note of when it was last reviewed

### PR DESCRIPTION
**Pull request by bilhox**
This PR is an up-to-date review of my french translation created a year ago, I mainly changed some wording I was using which wasn't natural, and more importantly, I added a note at the end of the file saying when it was last reviewed.

### CODE REVIEW

**Comment by damusss** [comment]
@bilhox it's actually very similar to what I did, I only added an header line before. would you not agree it would be fitting?

**Comment by bilhox** [comment]
> @bilhox it's actually very similar to what I did, I only added an header line before. would you not agree it would be fitting?

yes, just add also an english version of the date like I did.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Review by TheRealGabHas — COMMENTED** [review]
I think all the changes are good, they make the reading process more natural.

**Review by ankith26 — APPROVED** [review]
Thanks!

**Pull request merged**
