### PR TITLE
Bump cython to 3.0.0

### PR DESCRIPTION
**Pull request by yunline**

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
I like the idea of getting on cython 3.0.0
I can't remember at this point, what happened to that one PR that was trying to get cython files generated as part of our build step?

**Comment by MyreMylar** [comment]
> I like the idea of getting on cython 3.0.0 I can't remember at this point, what happened to that one PR that was trying to get cython files generated as part of our build step?

It is here #1877

**Review by pmp-p — APPROVED** [review]
lgtm, also fixes cython3+emsdk latest wasm multiple compile errors for me

**Comment by Starbuck5** [comment]
Why not add `__reduce__` to the stubs instead of turning off pickling?

**Comment by yunline** [comment]
> Why not add `__reduce__` to the stubs instead of turning off pickling?

Classes like `Renderer` was unable to be picled ever before. And I believe few users need to pickle those objects.
So I think turning off pickling can be a better way than adding something that may mess up the stubs.

**Review by dr0id — APPROVED** [review]
if it works...

LGTM

**Comment by Starbuck5** [comment]
> Classes like Renderer was unable to be picled ever before. And I believe few users need to pickle those objects.
So I think turning off pickling can be a better way than adding something that may mess up the stubs.

It's not messing up the stubs to update them with a new method being created.

But it's okay good for now, you're right.

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Pull request merged**
