### PR TITLE
Make `copy` methods explicit for linting

### PR DESCRIPTION
**Pull request by damusss**
I get annoyed by the fact `Object().copy()` is _blue_ (variable color) while `Object().__copy__()` is _yellow_ (method color). I think the public API method should be rightfully have the method color along with the magic dunder API.

Am I really making a PR because of a method color in my specific IDE theme? Yes.

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
Maybe you don't have to do an invert at all, another option is to be explicit and use the full line in both variants

**Comment by damusss** [comment]
> Maybe you don't have to do an invert at all, another option is to be explicit and use the full line in both variants

Good idea, I just did that.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:

**Review by zoldalma999 — APPROVED** [review]
LGTM!

**Pull request merged**
