### PR TITLE
Implement `draw_triangle` and `draw_quad` in `pygame._sdl2`

### PR DESCRIPTION
**Pull request by avaxar**
(I did an oopsie in #1829 while trying to solve a merge conflict. To whom, who made `src_c/_sdl2` expose Cython-generated C files, your decision was a **BAD** idea.)

**PR pygame/pygame#3006 ported from the Illume-maintained pygame library**

This PR implements the relatively new `SDL_RenderGeometry` function from SDL 2.0.18. It lets the programmer draw primitives with `SDL_Renderer`--in turn, `pygame._sdl2.Renderer`. This PR implements the SDL function as: `pygame._sdl2.Texture.draw_triangle`, `pygame._sdl2.Texture.draw_quad`, `pygame._sdl2.Renderer.draw_triangle`, `pygame._sdl2.Renderer.fill_triangle`, `pygame._sdl2.Renderer.draw_quad`, `pygame._sdl2.Renderer.fill_quad`.

I also have added typehints as requested by @MyreMylar.

As a minor change, I've also made `res` variables in `video.pyx` be `cdef`'d with an `int` type, to squeeze an extra bit of performance.

# Example
image
```py
import pygame
import pygame._sdl2


pygame.init()

window = pygame._sdl2.Window("amogus", (1066, 600))
renderer = pygame._sdl2.Renderer(window, vsync=True)
surface = pygame.image.load("avaxar.png")
texture = pygame._sdl2.Texture.from_surface(renderer, surface)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            break

    renderer.draw_color = (0, 0, 0, 255)
    renderer.clear()

    renderer.draw_color = (255, 255, 255, 255)
    renderer.fill_triangle((50, 50), (200, 100), (50, 100))
    renderer.fill_quad((250, 50), (500, 50), (600, 400), (200, 400))

    renderer.draw_color = (255, 0, 0, 255)
    renderer.draw_triangle((50, 150), (200, 200), (50, 200))
    renderer.draw_quad((250, 150), (500, 150), (600, 500), (200, 500))

    texture.draw_triangle((700, 400), (900, 400), (700, 550))
    texture.draw_quad((600, 100), (900, 100), (1000, 300), (700, 300))

    renderer.present()
```

### CODE REVIEW

**Comment by oddbookworm** [comment]
I'm about to crash for the night, but I'll try to review this in the morning

**Comment by oddbookworm** [comment]
It works well for me, but I did come across a possible issue in degenerate cases where the points are colinear.
```
import pygame
import pygame._sdl2


pygame.init()

window = pygame._sdl2.Window("amogus", (1066, 600))
renderer = pygame._sdl2.Renderer(window, vsync=True)
surface = pygame.image.load("examples/data/alien1.png")
texture = pygame._sdl2.Texture.from_surface(renderer, surface)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            break

    renderer.draw_color = (255, 255, 255, 255)
    renderer.clear()
    
    renderer.draw_color = (255, 0, 0, 255)
    # this degenerate case does not draw anything, but I would expect a line to show up?
    renderer.fill_triangle((0, 0), (100, 100), (50, 50))
    # this does draw a line
    renderer.draw_triangle((0, 50), (100, 150), (50, 100))

    renderer.present()
```
out

**Comment by avaxar** [comment]
Well, that's on SDL's side, not ours. `draw_triangle` relies on `SDL_RenderDrawLines`; that's why it shows up.

**Review by oddbookworm — APPROVED** [review]
LGTM!

**Pull request merged**
