### PR TITLE
Remove pygame.fastevent

### LINKED ISSUE #1962: Drop fastevent

### PR DESCRIPTION
**Pull request by gresm**
Fixes #1962

### CODE REVIEW

**Review by pmp-p — APPROVED** [review]

**Review by novialriptide — APPROVED** [review]

**Review by ankith26 — APPROVED** [review]
LGTM! Thanks for the PR :tada:

**Comment by ankith26** [comment]
There are merge conflicts in here. If you are comfortable/interested in rebasing, go ahead. Or let me know if you want me to do it for you before merging :)

**Comment by gresm** [comment]
Merge conflicts resolved @ankith26

**Comment by novialriptide** [comment]
Thanks!

**Pull request merged**
