### PR TITLE
Bump SDL to 2.26.4 (along with other deps bumps)

### PR DESCRIPTION
**Pull request by ankith26**
Basically mac/manylinux companion of #1986 along with a bunch of other related dependency updates sprinked in for good measure.

This may conflict with my older #1997 (which may need more testing/tinkering) so I'd like this to be merged first

### CODE REVIEW

**Comment by Starbuck5** [comment]
This looks pretty straightforward, the deletion of jpeg seems like the strangest thing. I assume we were using libjpeg-turbo already and this just cleans up the unused libjpeg.

**Review by Starbuck5 — APPROVED** [review]
This looks good. I don't have easy access to a system to test this locally right now, so I haven't.

I'd like somebody to test the new wheels.

**Comment by oddbookworm** [comment]
Looks good on my side. Ran a few test scripts and I didn't notice any problems
```
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame-ce 2.2.0 (SDL 2.26.4, Python 3.10.9)
>>> pygame.init()
(5, 0)
>>> pygame.print_debug_info()
Platform:               Linux-6.2.2-MANJARO-x86_64-with-glibc2.37
System:                 Linux
System Version:         #3 SMP PREEMPT_DYNAMIC Tue Mar  7 16:08:02 CST 2023
Processor:
Architecture:           Bits: 64bit     Linkage: ELF
Driver:                 x11

Python:                 CPython
pygame version:         2.2.0
python version:         3.10.9

SDL versions:           Linked: 2.26.4  Compiled: 2.26.4
SDL Mixer versions:     Linked: 2.6.3   Compiled: 2.6.3
SDL Font versions:      Linked: 2.20.2  Compiled: 2.20.2
SDL Image versions:     Linked: 2.0.5   Compiled: 2.0.5
Freetype versions:      Linked: 2.13.0  Compiled: 2.13.0
```

**Review by oddbookworm — APPROVED** [review]

**Comment by oddbookworm** [comment]
I also validated this on my Mac. My testing didn't turn up any problems
```
>>> pygame.print_debug_info()
Platform:		macOS-11.7.4-x86_64-i386-64bit
System:			Darwin
System Version:		Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
Processor:		i386
Architecture:		Bits: 64bit	Linkage: 
Driver:			cocoa

Python:			CPython
pygame version:		2.2.0
python version:		3.11.2

SDL versions:		Linked: 2.26.4	Compiled: 2.26.4
SDL Mixer versions:	Linked: 2.6.3	Compiled: 2.6.3
SDL Font versions:	Linked: 2.20.2	Compiled: 2.20.2
SDL Image versions:	Linked: 2.0.5	Compiled: 2.0.5
Freetype versions:	Linked: 2.13.0	Compiled: 2.13.0
```

**Pull request merged**
