### PR TITLE
relax convert conditions

### PR DESCRIPTION
**Pull request by robertpfeiffer**
There is no reason convert() has to wait for the display to be initialised. If a parameter with the target surface is provided, we can always convert.

### CODE REVIEW

**Review by ankith26 — CHANGES_REQUESTED** [review]
A small versionchanged entry in the docs for this and a simple test addition for this behaviour would be nice to have.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Comment by robertpfeiffer** [comment]
@ankith26 I'll just change some convert tests to not create a window, is that OK?

**Comment by ankith26** [comment]
Yes, that would be cool

**Comment by Starbuck5** [comment]
Converted to a draft since it has some feedback left to resolve. Looks like a nice improvement!

**Review by ankith26 — APPROVED** [review]
Need to run the formatter on the changed file, but apart from that this PR LGTM. Thanks! :tada: 

PS: we now have `pre-commit` setup for handling the formatting

**Comment by robertpfeiffer** [comment]
Can anybody please tell me why the CI is failing, I don't see any failing tests and just red marks

**Comment by oddbookworm** [comment]
> Can anybody please tell me why the CI is failing, I don't see any failing tests and just red marks

Error code 3221225477 is a segfault, but I don’t know what segfaulted from the log

**Pull request merged**
