### PR TITLE
added example on how Window behaves with WINDOWCLOSE and QUIT events

### PR DESCRIPTION
**Pull request by MrValdez**
I've noticed that the new Window API have different behavior with events. I've updated the documentation to reflect this.

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
Thanks for contributing! :tada: 

Just a minor nitpick, can you format the lines to fit the 80/88 character limit?

**Comment by ankith26** [comment]
While building the html docs (with `py -m buildconfig docs`) I am getting the following warnings:

```
/[my_path]/pygame-ce/docs/reST/ref/window.rst:49: ERROR: Unexpected indentation.
/[my_path]/pygame-ce/docs/reST/ref/window.rst:65: ERROR: Unexpected indentation.
```

The `.. code-block:: python` part must not be indented relative to the text, and the python code should be intended only once. Also I believe there should be one empty line before according to the `rst` spec.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for contributing! :tada:

**Review by zoldalma999 — APPROVED** [review]
Looks good to me! Thanks for contributing!

**Pull request merged**
