### PR TITLE
Add basic pygame.typing unit test, remove problematic TypeAlias usage

### PR DESCRIPTION
**Pull request by ankith26**
To catch issues like #3149

### CODE REVIEW

**Review by damusss — APPROVED** [review]
Yeah, good idea. LGTM!

**Comment by ankith26** [comment]
I have implemented a commit fixing the issue in this PR.

For now, the best fix seems to be reverting the `TypeAlias` changes entirely. And when our minimum supported python version becomes 3.12 (which should about 3 years from now), we can consider using the new `type` keyword and the other fancy new typing stuff.

**Review by damusss — APPROVED** [review]
I agree. Still looking good to me

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Pull request merged**
