### PR TITLE
Scrap deprecation and reimplementation

### PR DESCRIPTION
**Pull request by oddbookworm**
Port of https://github.com/pygame/pygame/pull/3510. If the old scrap API is being deprecated, I'd like to get the deprecation warning out as soon as possible as well as the new API that replaces it

### CODE REVIEW

**Comment by MyreMylar** [comment]
Guess this needs updating to 2.1.4 now that it didn't make 2.1.3.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Comment by MyreMylar** [comment]
It looks like something went wrong on your fork's branch here:

https://github.com/oddbookworm/pygame-ce/tree/scrap

**Comment by oddbookworm** [comment]
@MyreMylar seems to be fixed now

**Pull request closed without merging**
