### PR TITLE
SDL3 support for pygame.system

### PR DESCRIPTION
**Pull request by Starbuck5**
A little bit more gnarly than I would like, but the code comment explains my approach here.

### CODE REVIEW

**Review by damusss — APPROVED** [review]
LGTM :)

**Review by ankith26 — CHANGES_REQUESTED** [review]
```c
SDL_Locale **
PG_GetPreferredLocales(int *num_locales)
{
#if SDL_VERSION_ATLEAST(3, 0, 0)
    return SDL_GetPreferredLocales(num_locales);
#elif SDL_VERSION_ATLEAST(2, 0, 14)
    SDL_Locale *locales = SDL_GetPreferredLocales();
    if (locales) {
        SDL_Locale *current_locale = locales;
        *num_locales = 0;
        /* The array is terminated when the language attribute of the last
         * struct in the array is NULL */
        while (current_locale->language) {
            (*num_locales)++;
            current_locale++;
        }
        return &locales;
    }
#endif
    return NULL;
}
```

Untested code, somewhat based on your idea but written so that it can be abstracted out in a separate function

**Comment by Starbuck5** [comment]
SDL2: array of SDL_locales
SDL3: array of pointers to SDL_locales

Is a pointer to an array of SDL_locales the same thing as an array of pointers to SDL_locales ?

This is what I was sidestepping worrying about with my implementation but would need to think about for your code suggestion.

**Comment by ankith26** [comment]
okay NVM my suggestion, they are probably not the same

**Review by ankith26 — APPROVED** [review]
LGTM, thanks :star2:

**Pull request merged**
