### PR TITLE
Update to SDL_image 2.8.2

### LINKED ISSUE #2650: Win10 libpng16-16.dll incompatibility - fixed with older DLL
Win10 Home Edition
pygame-ce 2.4.0
python  3.11.4
SDL 2.28.5

On an old laptop, I uninstalled pygame 2.5 and replaced with pygame-ce 2.4.0

My program failed to load on this line:

bg = pygame.image.load(img_path + "bg/" + "bg.png").convert() 

Error was a pop up OS window: "Entry point not found - The procedure entry point inflate/validate could not be loated in the dynamic link library [...] libpng16-16.dll"

libpng

The fix was to replace C:\Users<username>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame\libpng16-16.dll with an older version packaged with SDL 2.0.1 : SDL2_image-2.0.1-win32-x64.zip

I sourced that package from here: https://www.libsdl.org/projects/SDL_image/release/

Swapping the DLL between the above and the one packaged with pygame-ce replicates the error every time. As noted, pygame 2.5 did not cause the same issue on this laptpop.

Posting here just in case it helps somebody in future.  It seems to be a known issue going back years (obviously not directly related to pygame-ce!)  [ref: https://discourse.libsdl.org/t/sdl2-image-fails-loading-libpng-on-latest-versions-when-cross-compiling/24494 ]

### PR DESCRIPTION
**Pull request by Starbuck5**
I updated the libpng in the SDL_image windows bundle, so this fixes #2650 

Libpng now statically links to zlib, so the windows wheels no longer have any zlib DLL floating around.

### CODE REVIEW

**Review by pmp-p — APPROVED** [review]

**Review by ankith26 — COMMENTED** [review]
I'm not sure if `zlib1.dll` should be removed entirely? It is still not entirely clear if something else needs zlib, so potentially there could be a break on some systems where zlib isn't available outside?

**Comment by ankith26** [comment]
So I was not feeling super confident, and I decided to fire a fresh windows VM to give this PR a spin, and got the classic error that everyone hates
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\tests\__main__.py", line 143, in <module>
    run_and_exit(*args, **kwds)
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\tests\test_utils\run_tests.py", line 346, in run_and_exit
    total, fails = run(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\tests\test_utils\run_tests.py", line 303, in run
    raise AssertionError(
AssertionError: Something went wrong in the Test Machinery:
total: 2167 != untrusty_total: 2166
```
More details: This is a fresh windows 11 with nothing else but python 3.12 installed. However when I do `py -m pygame.tests.image_test` everything still passes

**Comment by ankith26** [comment]
Okay so the same issue happens with 2.4.0 too

**Comment by Starbuck5** [comment]
I wonder if we could modify the test runner so it could tell us what module segfaulted, or even what function segfaulted. That would be much more handy.

**Review by ankith26 — APPROVED** [review]
Okay, I figured that those fails are not really related to this PR at all, and this PR LGTM! Thanks :tada:

For completeness sake, this PR could also bump the `SDL_image` on mac/manylinux, but I could also do it in a future PR if you say so.

**Comment by Starbuck5** [comment]
> For completeness sake, this PR could also bump the SDL_image on mac/manylinux, but I could also do it in a future PR if you say so.

This PR does that already :)

**Comment by ankith26** [comment]
Oh mb I didn't scroll down completely :man_facepalming:

**Pull request merged**
