### PR TITLE
Add loop and fade options to pygame.mixer.channel.queue()

### PR DESCRIPTION
**Pull request by AntoineMamou**
This PR is related to this issue : https://github.com/pygame-community/pygame-ce/issues/3236

I added optionals argument loop and fade in chan_queue to let the user choose if he wants to play the sound in the queue with a loop or a fade effect. I also modified the callback function to play the sound with the good effect.

### CODE REVIEW

**Comment by damusss** [comment]
Is my GitHub tweaking, why does this PR also add angle and angle rad properties? did you mix some branches?
Anyways, I didn't look at the code in depth but I can notice the missing mixer tests and stubs. Also the comments explaining the code should be written in English, not French, so everyone can understand them.
Also Also while the docs explain the new parameters, they have not been added to the function signature a few lines above.

**Comment by AntoineMamou** [comment]
Yeah I probably mix some branch, sorry. Thanks for your comment, I'm going to change what I forgot.

**Comment by AntoineMamou** [comment]
Maybe this PR should be closed, idk

**Comment by MyreMylar** [comment]
> Maybe this PR should be closed, idk

OK, feel free to open a new one when you get your branches sorted out!

**Pull request closed without merging**
