### PR TITLE
Docs updates (mainly to mixer)

### PR DESCRIPTION
**Pull request by Starbuck5**
> The mixer module is optional and depends on SDL_mixer. Your program should test that :mod:`pygame.mixer` is available and initialized before using it.

It's part of our API. Any remotely compliant build of pygame-ce has this, it's not something to be afraid of. I don't expect people's programs to test for pygame.mixer.

> Pygame will default to reasonable values, but pygame cannot perform Sound resampling, so the mixer should be initialized to match the values of your audio resources.

Technically, true, pygame-ce does not perform resampling. But SDL does, and they will resample into the format of your audio resources, this is highly misleading.

### CODE REVIEW

**Review by yunline — APPROVED** [review]
LGTM

**Review by ankith26 — COMMENTED** [review]
I wonder if imageext, font and freetype should also be getting the same treatment? They are also in the same boat of being "technically optional but used fairly widely so not actually"

**Comment by Starbuck5** [comment]
> I wonder if imageext, font and freetype should also be getting the same treatment? They are also in the same boat of being "technically optional but used fairly widely so not actually"

I don't see any such blatantly outdated text in their documentations.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks :tada:

**Pull request merged**
