### PR TITLE
Added persian transaltion for README.rst

### PR DESCRIPTION
**Pull request by mmdmoa**
I translated the README.rst to Persian (فارسی) and put it into docs/readmes directory.

### CODE REVIEW

**Comment by Starbuck5** [comment]
Running this through Google translate, the last line is translated to "For more information about the license of each dependency, use the links below."

But there aren't any links below. It should say licenses are in the docs/licenses folder, like the English version.

**Comment by Starbuck5** [comment]
Also in Google Translate I see mentions of the "paygame" library, presumably you put a "sounded-out" version of pygame into persian text?

Is that better than leaving the word "pygame" in English in the middle of sentences?

**Comment by mmdmoa** [comment]
I'll start investigating this issues as soon as I'm back home

**Comment by mmdmoa** [comment]
> Also in Google Translate I see mentions of the "paygame" library, presumably you put a "sounded-out" version of pygame into persian text?
> 
> Is that better than leaving the word "pygame" in English in the middle of sentences?

Now that I think about it yes, it's better not to translate the libraries name to persian.

**Comment by mmdmoa** [comment]
@Starbuck5 I fixed the problems you mentioned

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Pull request merged**
