### PR TITLE
Raise macOS deployment target to 10.11

### PR DESCRIPTION
**Pull request by Starbuck5**
For SDL 2.26.5 and above. https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5

### CODE REVIEW

**Review by oddbookworm — APPROVED** [review]
LGTM!

**Comment by Starbuck5** [comment]
Just put the CIBW_ENVIRONMENT variables back onto one line and squashed. That's the force push. Just to not have that unnecessary change in the diff.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks! :moon_cake:

**Comment by oddbookworm** [comment]
I tested a wheel on an intel mac running MacOS 11.7.4, and it seems to work perfectly

**Pull request merged**
