### PR TITLE
Raise minimum supported SDL2 to 2.0.14

### LINKED ISSUE #3210: After dropping Python 3.8 we can go up to SDL 2.0.14
We base our SDL minimum versions on the oldest common Linux package repository.

```
Ubuntu Focal => Python 3.8 and SDL 2.0.10              (we are here)
Debian Bullseye => Python 3.9 and SDL 2.0.14           (next step)
Ubuntu Jammy => Python 3.10 and SDL 2.0.20
Debian Bookworm => Python 3.11 and SDL 2.26.5
Ubuntu Mantic => Python 3.11 and SDL 2.28.3
```

Python 3.8 removal: https://github.com/pygame-community/pygame-ce/pull/3143

### PR DESCRIPTION
**Pull request by ankith26**
fixes #3210

### CODE REVIEW

**Review by bilhox — APPROVED** [review]
LGTM!

**Review by damusss — APPROVED** [review]
Sure :)

**Review by Starbuck5 — APPROVED** [review]
I'm not really sure we need to remove the information from our docs, it's still useful information for people using old versions, just like old versionadded's and the like. But I'm not super against.

Thanks for the PR.

**Comment by ankith26** [comment]
I prefer the docs mentioning SDL as few times as possible, and I feel like bumping the minimum SDL version is a good time to clean up that info that probably benefits a super small fraction to begin with (and said fraction should ideally keep their distro version upto date anyways)

**Pull request merged**
