### PR TITLE
fix search page green background in dark theme

### PR DESCRIPTION
**Pull request by Notenlish**
fixes the weird bug that @yunline reported
image

Here's how it looks currently 
image

here's the light theme version: 
image

### CODE REVIEW

**Comment by NOTMEE12** [comment]
maybe make that searchbar longer to the length of the text (`Searching for multiple words...`) or make it centered, cause it's looks a lil' weird.

**Comment by Notenlish** [comment]
> maybe make that searchbar longer to the length of the text (`Searching for multiple words...`) or make it centered, cause it's looks a lil' weird.

I don't think centering it would make sense
image

**Comment by NOTMEE12** [comment]
Now I saw that the text is not centered.

**Review by yunline — APPROVED** [review]
LGTM

**Review by Starbuck5 — APPROVED** [review]
Fixes the problem.

**Pull request merged**
