### PR TITLE
add deepcopy capability to Surface

### PR DESCRIPTION
**Pull request by dr0id**

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada: 

I'm thinking, should this be documented? Nothing too much, just a one line entry?

**Comment by dr0id** [comment]
> I'm thinking, should this be documented? Nothing too much, just a one line entry?

Well, __copy__ isn't documented either. Not sure where it should be mentioned. Should some sentence be added to the documentation of copy()? Or as with the mask at class level?

**Comment by dr0id** [comment]
> I'm thinking, should this be documented? Nothing too much, just a one line entry?

Just added some line in the documentation.

**Review by Starbuck5 — APPROVED** [review]

**Review by MyreMylar — APPROVED** [review]
LGTM 👍 

Seems like a minor enough change to sneak into 2.3.2.

**Pull request merged**
