### PR TITLE
Use SequenceLike in geometry stubs

### PR DESCRIPTION
**Pull request by ankith26**
Separated out from #3143 for independent review

### CODE REVIEW

**Comment by Starbuck5** [comment]
So, I think a big part of the reason to separate out changes into separate PRs is so they can be merged at different times, not blocking each other. Are you planning to remove these changes from #3143?

Because right now this PR just blocks #3143, as far as I can tell. And #3211 just blocks #3128.

**Comment by ankith26** [comment]
This PR and #3211 are standalones that are not blocked. Once these are merged I will update the dependent PRs to unblock them

**Comment by Starbuck5** [comment]
Yes, they are not blocked, but they block the PRs they were separated from. Which I feel defeats the point of splitting them out.

**Comment by ankith26** [comment]
Well, you cant split them out AND not block each other. In an ideal world this PR should have been merged before #3143 was even started, but that didn't happen. But I don't mind rebasing #3143 again so it's fine for now IG

**Comment by MrRedstone058** [comment]
my pr https://github.com/pygame-community/pygame-ce/pull/3179 might or might not have to be changed as well.

**Comment by Starbuck5** [comment]
> Well, you cant split them out AND not block each other.

Why not?

These are two independent changes to the stubs.

Changing all instances of Tuple, Dict, List to tuple, dict, list
VS
Changing some instances from Sequence to SequenceLike.

**Comment by ankith26** [comment]
They are independent but do changes to the same line and git isn't smart enough to auto resolve those conflicts

Screenshot From 2024-11-03 16-16-56

**Comment by Starbuck5** [comment]
So whichever PR merges first will graciously let the second PR deal with the merge conflict. That's fine.

**Comment by ankith26** [comment]
Yeah but I do have a preference for this one being merged first because it's ready and small. The other one needs a push either way to address your other review comments

**Comment by Starbuck5** [comment]
I'm just saying the way you've set up these two PRs requires this to be merged first, when the changes are actually independent. I want to approve your other PR and not worry about this detail, let some geometry people take a look.

**Review by zoldalma999 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
