### PR TITLE
Added `abs` support for returning vector magnitude

### PR DESCRIPTION
**Pull request by Matiiss**
Fixes https://github.com/pygame-community/pygame-ce/issues/2153

### CODE REVIEW

**Comment by Starbuck5** [comment]
I think it's weird for abs() to do magnitude instead of just absolute-ifying each element.

**Comment by Matiiss** [comment]
But `abs(v.elementiwise())` already does that, this would be like duplicating an existing feature. And `|v|` tends to be used for vector magnitudes.

**Comment by Starbuck5** [comment]
> But abs(v.elementiwise()) already does that, this would be like duplicating an existing feature. And |v| tends to be used for vector magnitudes.

Several ways to do something? What is this, pygame?

**Comment by MyreMylar** [comment]
> I think it's weird for abs() to do magnitude instead of just absolute-ifying each element.

Googling around other Vector3/Vector2 implementations it seems about 50/50 whether `abs(vector)` (or `vector.abs()`) returns the length scalar, or another vector with each x,y,z element absifyed.

I don't really care about this, as I think I would personally use `.length' first before `.magnitude` and then `abs(vector)` if it existed dead last for achieving the goal of obtaining the length of a vector.

On the other hand, I can't think of a particularly compelling reason to ever get the elementwise `abs()` of a Vector right now. Is there one?

I would just side with whichever is most popular if there is any evidence either way.

**Pull request closed without merging**
