### PR TITLE
Fixed missing comma in README

### LINKED ISSUE #2870: Grammar: Missing comma in main Readme?
It looks like there's a comma missing between two of the names in your Credits section of the main Pygame Readme. See the screenshots below:

Screen Shot 2024-05-18 at 9 57 09 PM
Screen Shot 2024-05-18 at 9 58 04 PM

### PR DESCRIPTION
**Pull request by REX2626**
Fixes #2870

### CODE REVIEW

**Review by oddbookworm — APPROVED** [review]
Thanks for the contribution 🥳, this looks good to me

**Review by ankith26 — CHANGES_REQUESTED** [review]
Actually, I now noticed that the same issue exists on the different translations of the README (the files are in `docs/readmes`). Could you apply the same fix on all the files?

**Comment by REX2626** [comment]
It should be fixed on all the README translations now.

**Review by ankith26 — APPROVED** [review]
The updates LGTM

**Pull request merged**
