### PR TITLE
Implement swizzling for `pygame.Color`

### LINKED ISSUE #1919: Implementing swizzling RGBA values for `pygame.Color`
Taking pygame/pygame#3705 here...

# Description

 There should be a way to construct a new `pygame.Color` from joining multiple color channels of a `pygame.Color` together in respect to RGB(A), simply per a single property access, otherwise known as swizzling. This is alike to GLSL's [swizzling](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling), where one could construct a vector from another by joining the values of multiple axes in a single identifier (i.e `my_vec.xyz` instead of `vec3(my_vec.x, my_vec.y, my_vec.z)`).

# Example Concept

```py
>>> color = pygame.Color(1, 2, 3, 4)
>>> color.rgb  # Alpha would still be specified optionally; `255` by default.
(1, 2, 3, 255)
>>> color.bgr
(3, 2, 1, 255)
>>> color.rrr
(1, 1, 1, 255)
>>> color.arar
(4, 1, 4, 1)
>>> color.brag
(3, 1, 4, 2)
>>> color.grab
(2, 1, 4, 3)
```

# Notes

 Though, yes, I am aware how many attributes would need to be implemented in C for every single case. Assuming that we'd be supporting combining 3 and 4 axes, that means 4^3 + 4^4 = 320 cases that would need to be implemented. It could be shrunk down to 4^4 = 256 cases if we use default args for the alpha channel for the other 4^3 cases. And we could shrink it even more into one packed function if we hijack `__getattr__`.

### PR DESCRIPTION
**Pull request by avaxar**
Continuing from #1926. Should close #1919.

This PR implements attribute swizzling for `pygame.Color`, similar to `pygame.Vector2` and `pygame.Vector3`.

I still have to give credit for @ScriptLineStudios for stealing the code for the unittests and typestubs.

### CODE REVIEW

**Comment by oddbookworm** [comment]
Looks like you have a small error preventing the checks from passing (at a quick glance)
image

**Comment by avaxar** [comment]
@oddbookworm I had blindly copied the code that should've been used for `double`s there. It's nice that the warning's there.

**Comment by avaxar** [comment]
Force-pushed too much, lol. There were just too many meaningless stupid mistakes I did that I wouldn't bother add to the commit line.

**Comment by avaxar** [comment]
Should I remove the typestubs for `__getattr__` and `__setattr__`? They're causing the CI to fail. Plus, I see that `pygame.Vector[2|3]` doesn't have such stubs.

**Comment by oddbookworm** [comment]
Vector[2,3] is a bit odd because they're inheriting from _GenericVector, which does have those stubs https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/stubs/pygame/math.pyi#L36-L39

**Comment by avaxar** [comment]
Those are `__setitem__` and `__getitem__`, not `__setattr__` nor `__getattr__`.

**Comment by oddbookworm** [comment]
Hmmmm, I guess __getattr__ isn't registering correctly or something?
```
>>> pprint(pygame.Color.__dict__)
mappingproxy({'__add__': <slot wrapper '__add__' of 'pygame.color.Color' objects>,
              '__array_struct__': <attribute '__array_struct__' of 'pygame.color.Color' objects>,
              '__contains__': <slot wrapper '__contains__' of 'pygame.color.Color' objects>,
              '__delattr__': <slot wrapper '__delattr__' of 'pygame.color.Color' objects>,
              '__delitem__': <slot wrapper '__delitem__' of 'pygame.color.Color' objects>,
              '__doc__': 'Color(r, g, b) -> Color\n'
                         'Color(r, g, b, a=255) -> Color\n'
                         'Color(color_value) -> Color\n'
                         'pygame object for color representations',
              '__eq__': <slot wrapper '__eq__' of 'pygame.color.Color' objects>,
              '__float__': <slot wrapper '__float__' of 'pygame.color.Color' objects>,
              '__floordiv__': <slot wrapper '__floordiv__' of 'pygame.color.Color' objects>,
              '__ge__': <slot wrapper '__ge__' of 'pygame.color.Color' objects>,
              '__getattribute__': <slot wrapper '__getattribute__' of 'pygame.color.Color' objects>,
              '__getitem__': <slot wrapper '__getitem__' of 'pygame.color.Color' objects>,
              '__gt__': <slot wrapper '__gt__' of 'pygame.color.Color' objects>,
              '__hash__': None,
              '__index__': <slot wrapper '__index__' of 'pygame.color.Color' objects>,
              '__init__': <slot wrapper '__init__' of 'pygame.color.Color' objects>,
              '__int__': <slot wrapper '__int__' of 'pygame.color.Color' objects>,
              '__invert__': <slot wrapper '__invert__' of 'pygame.color.Color' objects>,
              '__iter__': <slot wrapper '__iter__' of 'pygame.color.Color' objects>,
              '__le__': <slot wrapper '__le__' of 'pygame.color.Color' objects>,
              '__len__': <slot wrapper '__len__' of 'pygame.color.Color' objects>,
              '__lt__': <slot wrapper '__lt__' of 'pygame.color.Color' objects>,
              '__mod__': <slot wrapper '__mod__' of 'pygame.color.Color' objects>,
              '__mul__': <slot wrapper '__mul__' of 'pygame.color.Color' objects>,
              '__ne__': <slot wrapper '__ne__' of 'pygame.color.Color' objects>,
              '__new__': <built-in method __new__ of type object at 0x00007FF970709460>,
              '__radd__': <slot wrapper '__radd__' of 'pygame.color.Color' objects>,
              '__repr__': <slot wrapper '__repr__' of 'pygame.color.Color' objects>,
              '__rfloordiv__': <slot wrapper '__rfloordiv__' of 'pygame.color.Color' objects>,
              '__rmod__': <slot wrapper '__rmod__' of 'pygame.color.Color' objects>,
              '__rmul__': <slot wrapper '__rmul__' of 'pygame.color.Color' objects>,
              '__rsub__': <slot wrapper '__rsub__' of 'pygame.color.Color' objects>,
              '__setattr__': <slot wrapper '__setattr__' of 'pygame.color.Color' objects>,
              '__setitem__': <slot wrapper '__setitem__' of 'pygame.color.Color' objects>,
              '__sub__': <slot wrapper '__sub__' of 'pygame.color.Color' objects>,
              'a': <attribute 'a' of 'pygame.color.Color' objects>,
              'b': <attribute 'b' of 'pygame.color.Color' objects>,
              'cmy': <attribute 'cmy' of 'pygame.color.Color' objects>,
              'correct_gamma': <method 'correct_gamma' of 'pygame.color.Color' objects>,
              'g': <attribute 'g' of 'pygame.color.Color' objects>,
              'hsla': <attribute 'hsla' of 'pygame.color.Color' objects>,
              'hsva': <attribute 'hsva' of 'pygame.color.Color' objects>,
              'i1i2i3': <attribute 'i1i2i3' of 'pygame.color.Color' objects>,
              'lerp': <method 'lerp' of 'pygame.color.Color' objects>,
              'normalize': <method 'normalize' of 'pygame.color.Color' objects>,
              'premul_alpha': <method 'premul_alpha' of 'pygame.color.Color' objects>,
              'r': <attribute 'r' of 'pygame.color.Color' objects>,
              'set_length': <method 'set_length' of 'pygame.color.Color' objects>,
              'update': <method 'update' of 'pygame.color.Color' objects>})
```

**Comment by avaxar** [comment]
As `__getattribute__`? I'm going to add back the stubs with that.

**Comment by oddbookworm** [comment]
Is this intended?
```
>>> c = pygame.Color(1,2,3,4)
pygame-ce 2.1.4.dev1 (SDL 2.0.22, Python 3.11.1)
>>> c.rga
(1, 2, 4, 255)
>>> c.rgb
(1, 2, 3, 255)
```

**Comment by avaxar** [comment]
Yes. Like how you initialize a `Color` instance by `pygame.Color(r, g, b)`, it sets the alpha by default to 255 (opaque).

**Review by oddbookworm — CHANGES_REQUESTED** [review]
Everything looks good and I haven't found any problems while testing. I am requesting one more thing:
add color swizzling documentation please

**Review by MyreMylar — APPROVED** [review]
Overall looks good. 

I agree that it needs a bit of documentation on what swizzling e.g. (https://en.wikipedia.org/wiki/Swizzling_(computer_graphics)) along with a worked example. Probably make it clear it is just rgba swizzling and not cmy, hsla, hsva or i1i2i3 which are also available as attributes of Color.

Otherwise, it works well. 

My test program:

```
import pygame

test_col = pygame.Color(255, 100, 50, 200)

print(test_col)
print(test_col.rgb)
print(test_col.rg)
print(test_col.bgra)

new_col = test_col.bgr
print(new_col)
print(test_col)

test_col.rgb = (128, 126, 127)
print(test_col)
```

Output (as expected):
```
<Color(255, 100, 50, 200)>
<Color(255, 100, 50, 255)>
(255, 100)
<Color(50, 100, 255, 200)>
<Color(50, 100, 255, 255)>
<Color(255, 100, 50, 200)>
<Color(128, 126, 127, 200)>
```
Well done!

**Review by oddbookworm — APPROVED** [review]
LGTM!

**Pull request merged**
