### PR TITLE
Fix for windows cameras without framerate

### PR DESCRIPTION
**Pull request by Starbuck5**
Issue reported by Pallas's cat on discord.

`pygame.error: Media Foundation HRESULT failure -1072875802 on camera_windows.c line 407`

This should fix it, waiting on testing by them.

### CODE REVIEW

**Comment by bilhox** [comment]
With the fix, I get this new error :
```powershell
  File "c:\Users\lodyB\OneDrive\Documents\workspace python\starbucks_pygame\examples\camera.py", line 47, in init_cams
    self.camera.start()
SystemError: <method 'start' of 'pygame.camera.Camera' objects> returned NULL without setting an exception
```

**Comment by Starbuck5** [comment]
Makes sense...

Try this one: 
[pygame_ce-2.4.0.dev3-cp312-cp312-win_amd64.zip](https://github.com/pygame-community/pygame-ce/files/13404698/pygame_ce-2.4.0.dev3-cp312-cp312-win_amd64.zip)

**Comment by bilhox** [comment]
Oh my god I'm so beautifu uh uh uh, excuse me, tyvm, it works correctly now !

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Review by dr0id — APPROVED** [review]
LGTM

**Review by ankith26 — APPROVED** [review]
Fixes the issue for OP, and code LGTM. Thanks, let's get this in! :tada:

**Pull request merged**
