### PR TITLE
Remove obsolete vidcapture camera backend (#1660)

### PR DESCRIPTION
**Pull request by that1guy232**
#1660
I very much imagine I am missing things.

### CODE REVIEW

**Comment by Starbuck5** [comment]
This looks pretty good to go from me. The only thing I notice straight away is that the docs should have a note that support was removed in this pygame version.

See `..versionchanged:` tags in other bits of the codebase.

**Comment by that1guy232** [comment]
> The only other file I can find mentioning the Videocapture back end is here:
> 
> https://github.com/pygame-community/pygame-ce/blob/main/docs/reST/tutorials/en/intro-to-camera.rst
> 
> In the second paragraph/first 'Note' block.
> 
> > As of Pygame 1.9, the camera module offers native support for cameras that use v4l2 on Linux. There is support for other platforms via Videocapture or OpenCV, but this guide will focus on the native module.

Good catch, I Think I got the last of it!

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Review by novialriptide — APPROVED** [review]
LGTM.

**Pull request merged**
