### PR TITLE
Remove experimental notice on system module

### PR DESCRIPTION
**Pull request by Starbuck5**
We're going to treat this module with as much back-compat effort as anything else right now, so this notice is moot.

### CODE REVIEW

**Review by yunline — APPROVED** [review]
LGTM

**Review by ankith26 — COMMENTED** [review]
I'd like `get_power_state` to be in experimental state just in case something comes up (it hasn't seen a release yet)

I agree the rest should be leaving experimental status

**Comment by Starbuck5** [comment]
As requested, I added a more specific experimental notice there.

**Review by MyreMylar — APPROVED** [review]
LGTM

**Pull request merged**
