### PR TITLE
Optimized pgRect_FromObject

### PR DESCRIPTION
**Pull request by itzpr3d4t0r**
This PR improves the `pgRect_FromObject` function to handle number sequences faster. This affects Rect construction and any function that takes a Rect-like object as an argument.

## Results
Edited: I added more benchmarks for objects with rect attributes or methods (some results may deviate slightly from the previous ones but that's normal).
OLD
```
-) Rect instantiation 4 args: 155.2ms
-) Rect instantiation 1 arg: 159.4ms
-) Rect instantiation 2 args: 150.6ms
-) Rect instantiation 1 args 2 subtups: 164.0ms
-) Rect instantiation objwithrect: 276.3ms
-) Rect instantiation objwithrectmethod: 350.1ms

-) update 4 args: 132.9ms
-) update 1 arg: 141.6ms
-) update 2 args: 132.4ms
-) update 1 args 2 subtups: 145.0ms
-) update objwithrect: 254.3ms
-) update objwithrectmethod: 329.2ms

-) union 4 args: 155.3ms
-) union 1 arg: 165.4ms
-) union 2 args: 156.6ms
-) union 1 arg 2 subtups: 172.3ms
-) union objwithrect: 287.6ms
-) union objwithrectmethod: 338.6ms

-) union_ip 4 args: 133.9ms
-) union_ip 1 arg: 140.6ms
-) union_ip 2 args: 130.7ms
-) union_ip 1 arg 2 subtups: 143.4ms
-) union_ip objwithrect: 247.7ms
-) union_ip objwithrectmethod: 315.9ms

-) clip 4 args: 150.6ms
-) clip 1 arg: 159.7ms
-) clip 2 args: 147.2ms
-) clip 1 arg 2 subtups: 162.6ms
-) clip objwithrect: 280.3ms
-) clip objwithrectmethod: 333.1ms

-) colliderect 4 args: 62.2ms
-) colliderect 1 arg: 102.2ms
-) colliderect 2 args: 91.5ms
-) colliderect 1 arg 2 subtups: 112.0ms
-) colliderect objwithrect: 202.9ms
-) colliderect objwithrectmethod: 275.0ms

-) collidelist 1 arg: 1000.0ms
-) collidelist 1 arg 2 subtups: 1213.8ms

-) collidelistall 1 arg: 1122.4ms
-) collidelistall 1 arg 2 subtups: 1359.8ms
```

NEW
```
-) Rect instantiation 4 args: 121.8ms
-) Rect instantiation 1 arg: 130.2ms
-) Rect instantiation 2 args: 147.0ms
-) Rect instantiation 1 args 2 subtups: 162.9ms
-) Rect instantiation objwithrect: 206.2ms
-) Rect instantiation objwithrectmethod: 257.3ms

-) update 4 args: 118.9ms
-) update 1 arg: 114.7ms
-) update 2 args: 129.1ms
-) update 1 args 2 subtups: 142.3ms
-) update objwithrect: 184.4ms
-) update objwithrectmethod: 254.7ms

-) union 4 args: 132.3ms
-) union 1 arg: 131.8ms
-) union 2 args: 143.5ms
-) union 1 arg 2 subtups: 161.9ms
-) union objwithrect: 203.2ms
-) union objwithrectmethod: 270.4ms

-) union_ip 4 args: 104.7ms
-) union_ip 1 arg: 106.7ms
-) union_ip 2 args: 127.7ms
-) union_ip 1 arg 2 subtups: 143.0ms
-) union_ip objwithrect: 182.3ms
-) union_ip objwithrectmethod: 244.1ms

-) clip 4 args: 133.7ms
-) clip 1 arg: 129.4ms
-) clip 2 args: 153.6ms
-) clip 1 arg 2 subtups: 177.9ms
-) clip objwithrect: 219.3ms
-) clip objwithrectmethod: 273.4ms

-) colliderect 4 args: 64.3ms
-) colliderect 1 arg: 80.3ms
-) colliderect 2 args: 90.8ms
-) colliderect 1 arg 2 subtups: 107.3ms
-) colliderect objwithrect: 153.3ms
-) colliderect objwithrectmethod: 204.2ms

-) collidelist 1 arg: 707.2ms
-) collidelist 1 arg 2 subtups: 1230.5ms

-) collidelistall 1 arg: 752.2ms
-) collidelistall 1 arg 2 subtups: 1273.5ms
```
I used this test program:
```Python
import timeit
from statistics import fmean

from pygame.rect import Rect

NUMBER = 1_000_000

r1 = Rect(799, 799, 10, 10)
r2 = Rect(0, 0, 5, 5)
rects = [
    (0, 0, 100, 100),
    (50, 50, 100, 100),
    (100, 100, 100, 100),
    (150, 150, 100, 100),
    (200, 200, 100, 100),
    (250, 250, 100, 100),
    (300, 300, 100, 100),
    (350, 350, 100, 100),
    (400, 400, 100, 100),
    (450, 450, 100, 100),
    (500, 500, 100, 100),
    (550, 550, 100, 100),
    (600, 600, 100, 100),
    (650, 650, 100, 100),
    (700, 700, 100, 100),
]
rects2 = [((a, b), (c, d)) for a, b, c, d in rects]


class RectAttr:
    def __init__(self, x, y, w, h):
        self.rect = Rect(x, y, w, h)


r3 = RectAttr(799, 799, 10, 10)


class RectMethod:
    def __init__(self, x, y, w, h):
        self.p = Rect(x, y, w, h)

    def rect(self):
        return self.p


r4 = RectMethod(799, 799, 10, 10)

GLOB = globals()


def test(test_name: str, func: str) -> None:
    value = fmean(timeit.repeat(func, globals=GLOB, number=NUMBER))
    print("-) " + test_name + f": {value * 1000:.1f}ms")


test("Rect instantiation 4 args", "Rect(10.0, 10.0, 2.0, 2.0)")
test("Rect instantiation 1 arg", "Rect((10.0, 10.0, 2.0, 2.0))")
test("Rect instantiation 2 args", "Rect((10.0, 10.0), (2.0, 2.0))")
test("Rect instantiation 1 args 2 subtups", "Rect(((10.0, 10.0), (2.0, 2.0)))")
test("Rect instantiation objwithrect", "Rect(r3)")
test("Rect instantiation objwithrectmethod", "Rect(r4)")
print()
test("update 4 args", "r1.update(10.0, 10.0, 2.0, 2.0)")
test("update 1 arg", "r1.update((10.0, 10.0, 2.0, 2.0))")
test("update 2 args", "r1.update((10.0, 10.0), (2.0, 2.0))")
test("update 1 args 2 subtups", "r1.update(((10.0, 10.0), (2.0, 2.0)))")
test("update objwithrect", "r1.update(r3)")
test("update objwithrectmethod", "r1.update(r4)")
print()
test("union 4 args", "r1.union(10.0, 10.0, 2.0, 2.0)")
test("union 1 arg", "r1.union((10.0, 10.0, 2.0, 2.0))")
test("union 2 args", "r1.union((10.0, 10.0), (2.0, 2.0))")
test("union 1 arg 2 subtups", "r1.union(((10.0, 10.0), (2.0, 2.0)))")
test("union objwithrect", "r1.union(r3)")
test("union objwithrectmethod", "r1.union(r4)")
print()
test("union_ip 4 args", "r2.union_ip(10.0, 10.0, 2.0, 2.0)")
test("union_ip 1 arg", "r2.union_ip((10.0, 10.0, 2.0, 2.0))")
test("union_ip 2 args", "r2.union_ip((10.0, 10.0), (2.0, 2.0))")
test("union_ip 1 arg 2 subtups", "r2.union_ip(((10.0, 10.0), (2.0, 2.0)))")
test("union_ip objwithrect", "r2.union_ip(r3)")
test("union_ip objwithrectmethod", "r2.union_ip(r4)")
print()
test("clip 4 args", "r1.clip(10.0, 10.0, 2.0, 2.0)")
test("clip 1 arg", "r1.clip((10.0, 10.0, 2.0, 2.0))")
test("clip 2 args", "r1.clip((10.0, 10.0), (2.0, 2.0))")
test("clip 1 arg 2 subtups", "r1.clip(((10.0, 10.0), (2.0, 2.0)))")
test("clip objwithrect", "r1.clip(r3)")
test("clip objwithrectmethod", "r1.clip(r4)")
print()
test("colliderect 4 args", "r1.colliderect(10.0, 10.0, 2.0, 2.0)")
test("colliderect 1 arg", "r1.colliderect((10.0, 10.0, 2.0, 2.0))")
test("colliderect 2 args", "r1.colliderect((10.0, 10.0), (2.0, 2.0))")
test("colliderect 1 arg 2 subtups", "r1.colliderect(((10.0, 10.0), (2.0, 2.0)))")
test("colliderect objwithrect", "r1.colliderect(r3)")
test("colliderect objwithrectmethod", "r1.colliderect(r4)")
print()
test("collidelist 1 arg", "r1.collidelist(rects)")
test("collidelist 1 arg 2 subtups", "r1.collidelist(rects2)")
print()
test("collidelistall 1 arg", "r1.collidelistall(rects)")
test("collidelistall 1 arg 2 subtups", "r1.collidelistall(rects2)")
```

### CODE REVIEW

**Review by MyreMylar — COMMENTED** [review]
Hmm, 

On my machine testing the above I got a consistent pattern:

```
pygame-ce 2.1.4.dev1 (SDL 2.0.22, Python 3.11.1) - main
-) Rect instantiation:  faster with PR
-) Rect instantiation 1 arg:  faster with PR
-) Rect instantiation 2 args:  slower with PR
-) Rect instantiation 1 args 2 subtups: slower with PR

-) update:  faster
-) update 1 arg:  faster
-) update 2 args:  slower
-) update 1 args 2 subtups:  slower

-) union: faster
-) union 1 arg: faster
-) union 2 args:  slower
-) union 1 arg 2 subtups: slower

-) clip: faster
-) clip 1 arg:  faster
-) clip 2 args:  slower
-) clip 1 arg 2 subtups:  slower
```

Has something gone wrong here? Or am I just getting a freak result?

**Comment by itzpr3d4t0r** [comment]
Depends on how much slower that is. I retested it and yeah apparently the pattern repeats with me as well, but the difference is minimal most of the times, so it might be in the noise. When i tested this in the first comment i just copied my old result from the old PR.... I'm starting to suspect that when i did that i had python 3.10 and now i'm testing with 3.11.

**Comment by itzpr3d4t0r** [comment]
I might try to work on this one a bit more.

**Review by MyreMylar — APPROVED** [review]
OK, LGTM now. I get similar speed ups locally to those you posted above, 👍

**Comment by itzpr3d4t0r** [comment]
I'm closing this because of the changes that were made to the rect module. I'll be opening a new PR containing the changes.

**Pull request closed without merging**
