### PR TITLE
Fix grub-efi-amd64-signed installation failures on Ubuntu 20.04 CI builds

### PR DESCRIPTION
**Pull request by MyreMylar**
The full error looks like this:

```
Setting up grub-efi-amd64-signed (1.187.6~20.04.1+2.06-2ubuntu14.4) ...
mount: /var/lib/grub/esp: special device /dev/disk/by-id/scsi-14d53465420202020d8446e3f9983954098f1e80336f3baf3-part15 does not exist.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 32
```

See: https://github.com/orgs/community/discussions/47863
See also: https://github.com/actions/runner-images/issues/7192

May have to try a few things here.

### CODE REVIEW

**Comment by MyreMylar** [comment]
This issue happened before back in Feb/March and we added a temp fix, then [pulled it out again](https://github.com/pygame-community/pygame-ce/pull/2012) when Github resolved it.

It is happening again this week (several days now) so I propose we pop the temp fix back in until it is again resolved by Github. I've updated our original bug thread about it, in case that makes a difference.

This time I also tried a couple of other temp fixes I saw posted on the Github Actions repo - however the only one that worked here was our original temp fix.

**Review by oddbookworm — APPROVED** [review]
LGTM!

**Review by Temmie3754 — APPROVED** [review]
LGTM 👍

**Review by ankith26 — APPROVED** [review]
LGTM, lets get this in ASAP

**Pull request merged**
