### PR TITLE
Fixed mouse.set_pos under wayland

### PR DESCRIPTION
**Pull request by mzivic7**
I found the reason why mouse.set_pos() is not working under wayland (xwyland), in one of blender [bug reports](https://projects.blender.org/blender/blender/issues/53004#issuecomment-551561):
> The issue is that the cursor cannot be warped as long as it is visible. The way things work currently is, if a cursor is hidden and it is warped, we lie to X11 clients and say it is actually warped. While doing so, we lock the pointer via the available Wayland protocols. When the cursor is made visible or that for some other reason the lock is broken (for example the user Alt-tab:ed away), we stop lying and where the visible cursor is displayed is the position we tell the clients about. This works for the majority of use cases we have run into (including Blender uses, excluding the one discussed in this report).
We handle confinement in a more direct way.
In other words, if the patch implements a behavior where the pointer cursor is warped while visible, it wont work. If the pointer cursor is confined using X11 protocol, or hidden then warped, and it doesn't work, it could very much be an Xwayland issue.

I tried this:
```py
pygame.mouse.set_visible(False)
pygame.mouse.set_pos(300, 300)
pygame.mouse.set_visible(True)
```
and it worked!

So, I just added `PG_HideCursor();` before and `PG_ShowCursor();` after [this](https://github.com/pygame-community/pygame-ce/blob/main/src_c/mouse.c#L61) line.

### CODE REVIEW

**Comment by mzivic7** [comment]
Closes #2799

**Comment by mzivic7** [comment]
I  reported issue upstream to SDL: [here](https://github.com/libsdl-org/SDL/issues/9539)

**Comment by Starbuck5** [comment]
So SDL has fixed it, but only for SDL3. Great research and effort @mzivic7!

I just asked on your issue there whether they think it's worth back-porting to SDL2. If they do back-port, I say we let them handle this hack instead of putting it into our own code.

If they don't want to back-port, we'll have to think further about how much we care about this. One thing for sure though, if we put this into our code I want comments in the codebase explaining exactly why.

**Comment by ankith26** [comment]
Update: the SDL devs have backported the fix to SDL2

Thanks @mzivic7 for reporting the issue upstream and suggesting the fix. Now to get this fix on our side we just gotta bump SDL when they release the next release.

**Comment by mzivic7** [comment]
Great, I will close this pr and issue, since this is no longer related to pygame-ce code.

**Pull request closed without merging**
