### PR TITLE
Addresses some concerns from #1924

### PR DESCRIPTION
**Pull request by novialriptide**

### CODE REVIEW

**Review by MyreMylar — APPROVED** [review]
LGTM 👍 

Tutorials all build and work in my testing.

**Comment by MyreMylar** [comment]
looks like a few merge conflicts that need fixing now though.

**Comment by novialriptide** [comment]
Merge went smoothly without any manual merging needed.

**Review by yunline — APPROVED** [review]
LGTM OYRFFJ4U9L _S%O)4ZAG2(R

**Review by ankith26 — APPROVED** [review]
Didn't test locally, but on a glance it looks aight. Thanks! :taco:

**Pull request merged**
