### PR TITLE
Smoothscale: deprecate old backends, update docs

### PR DESCRIPTION
**Pull request by Starbuck5**
Follows on from story started in #2473 and #2544.

The old backends are marked deprecated. I don't want to remove them yet in case bugs are found in the new implementations. Having the old ones around allows users to work around by setting it to use the old ones explicitly.

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
Would be also nice to have a unit test testing the deprecation

**Comment by Starbuck5** [comment]
> Would be also nice to have a unit test testing the deprecation

I thought of this but I didn't include it initially since it seems very minor, I've included it now.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:

**Pull request merged**
