### PR TITLE
Debug method

### PR DESCRIPTION
**Pull request by oddbookworm**
port of https://github.com/pygame/pygame/pull/3374

### CODE REVIEW

**Comment by MyreMylar** [comment]
Huh, I can't re-open this one to trigger the CI for some reason.

**Comment by MyreMylar** [comment]
@oddbookworm maybe you can re-open it?

**Review by Matiiss — CHANGES_REQUESTED** [review]
Seems to be functional, I get all the debug info, so that's great. 👍 

Mainly would be great if you could add docstrings as seemingly most functions in `src_py` have them, so for consistency, they should be added here too.

**Review by Matiiss — APPROVED** [review]
LGTM, nice feature 👍

**Review by MyreMylar — APPROVED** [review]
LGTM 👍 

current output:

```
Platform:		Windows-10-10.0.22621-SP0
System:			Windows
System Version:		10.0.22621
Processor:		AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
Architecture:		Bits: 64bit	Linkage: WindowsPE
Driver:			windows

Python:			CPython
pygame version:		2.1.4.dev1
python version:		3.11.1

SDL versions:		Linked: 2.0.22	Compiled: 2.0.22
SDL Mixer versions:	Linked: 2.6.2	Compiled: 2.6.2
SDL Font versions:	Linked: 2.20.1	Compiled: 2.20.1
SDL Image versions:	Linked: 2.0.5	Compiled: 2.0.5
Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1
```

**Pull request merged**
