### PR TITLE
Updated SDL to 2.30.3

### PR DESCRIPTION
**Pull request by oddbookworm**

### CODE REVIEW

**Comment by oddbookworm** [comment]
Closing and reopening due to possible spurious failure

**Comment by Starbuck5** [comment]
>  Closing and reopening due to possible spurious failure.

You can re run these things by pressing a button!

**Comment by Damus666** [comment]
> You can re run these things by pressing a button!
@Starbuck5  What permission level has this button? (just to make sure I am not blind)

**Comment by Starbuck5** [comment]
@Damus666 You're not a member of the pygame-community org on GitHub, you don't have permissions for this.

**Comment by Damus666** [comment]
> @Damus666 You're not a member of the pygame-community org on GitHub, you don't have permissions for this.

Okay thanks, I was just making sure of it :)

**Review by Starbuck5 — APPROVED** [review]
Gave it a local test for good measure, it passed.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada:

**Pull request merged**
