### PR TITLE
Add example for retro scaling

### PR DESCRIPTION
**Pull request by snowfruit**
Add file "retro_scaling.py" that shows how to render to a surface and scale it to achieve a retro look.

### CODE REVIEW

**Review by ankith26 — CHANGES_REQUESTED** [review]
Hello, thanks for contributing! :partying_face: 

We use `black` for keeping our code formatted, please run `python3 setup.py format` and commit the resulting changes.

**Comment by robertpfeiffer** [comment]
Hmm. As is, this duplicates existing functionality, but it could be useful as a "Rosetta Stone" if we add another example based on Window and Texture, to show how one would to this with SDL2 machinery.

**Comment by snowfruit** [comment]
> Hello, thanks for contributing! 🥳
> 
> We use `black` for keeping our code formatted, please run `python3 setup.py format` and commit the resulting changes.

I thought I did. I will try again.

**Comment by snowfruit** [comment]
> Hmm. As is, this duplicates existing functionality, but it could be useful as a "Rosetta Stone" if we add another example based on Window and Texture, to show how one would to this with SDL2 machinery.

Are you referring to pygame.SCALED?

**Comment by snowfruit** [comment]
> Yeah, if you're up for it. As is, there are many use cases deliberately not covered by SCALED, and rather than having people poke around in the innards of the display module like @Matiiss likes to do (which could break at any time with the next release), it would make more sense to implement SCALED on top of pygame.Window. Maybe somebody wants to have the background a repeating pattern instead of black, or a nine-patch pattern, or just a different colour. Maybe somebody wants to use SCALED but really, really wants to control the size of the window. Something like that is probably within your abilities (you already did it once) and could be really useful.

I have no idea how that would be done. I don't have the skills for something like that. But my code here https://github.com/snowfruit/pygame-addons/tree/main/pygame_screen might spark some ideas for a person who knows how.

**Comment by snowfruit** [comment]
> Hello, thanks for contributing! 🥳
> 
> We use `black` for keeping our code formatted, please run `python3 setup.py format` and commit the resulting changes.

I did the `python3 setup.py format` on the file. I used the web-interface and hope the file is in the right format now. I think the next step is to press the "Re-request review"-button so that's what I will do.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR :tada: 

I think we could potentially expand this in the future to maybe become more interactive, or integrate it into a bigger example. For now I don't mind merging this change in its current state.

**Review by oddbookworm — APPROVED** [review]
LGTM

**Pull request merged**
