### PR TITLE
Addition of CONTRIBUTING.md for project repo

### PR DESCRIPTION
**Pull request by MrF1ow**
### Why Change was Made
Sifting through all the project docs to figure out how to contribute was a bit of a maze. It took some digging and hopping between wiki pages to find what I needed. But, I realized that having everything I need in one spot would've made life a whole lot easier for me and other contributors, old and new. It's like a roadmap that guides you straight to the goods without all the detours. So, consolidating all that vital info in one place really sets the stage for a smoother ride for everyone involved!

### Why pygame CE should accept changes

If pygame CE accepts these changes, I know that it will speed-up the onboarding process for contributors, making it more inviting for new folks to jump in and for seasoned contributors to navigate with ease. Additionally, it will lessen the amount of questions people have about how to get started or where to find essential information. It is a win-win all around!

### What I Did
Here is what was added and changed:
- A CONTRIBUTING.md file was added to the top level of the project repo
- In this new file, information that was spread throughout the wiki pages regarding contributing to the project was put into one document and formatted for ease of understanding and readability. 
- Most of the text and such is from the wiki pages and is not changed.
- With the project seeming very friendly and kind, I really tried to emphasize that through the altered and additional text that was added..
- A small "How To Contribute" section was added to the README.rst file that directs the user to this new CONTRIBUTING.md file. Note about this, the link will not work unless it is in the main project repo.

#2883

### CODE REVIEW

**Comment by novialriptide** [comment]
I took a quick skim; this all looks good, but I think we (as in the pygame community members) should be the ones to write all of this. Seeing as this is your first contribution, I'd say it's a little inappropriate that you're the one writing this. Although if the others agree with this, my first takeaway is that this should be a reStructuredText file.

**Comment by MrF1ow** [comment]
I hardly wrote any of it. It is 98% what was written in the wiki pages. I just collected it all into one document. Just makes it easier to find and navigate.

**Comment by MyreMylar** [comment]
> I totally understand that. Just so you know though I hardly wrote any of it. **It is 98% what was written in the wiki pages.** I just collected it all into one document.

I think this cuts to the heart of this. I think we should have a CONTRIBUTING.md file, but it should be brief and largely be composed of links to our existing documentation on the Wiki - otherwise we are just duplicating text in two places that we then have to maintain.

Pygame is older than Github and historically the contribution documentation has been on a wiki like page so I'd like to continue that tradition. I think we can accomodate people who search for a CONTRIBUTING.md file by just linking them to the existing documentation and making any improvements needed over there.

Does that make sense? I don't want to be updating text in two places as things change.

Here is an example of another large project (numpy) that takes this approach with CONTRIBUTING.md:

[https://github.com/numpy/numpy/blob/main/.github/CONTRIBUTING.md](https://github.com/numpy/numpy/blob/main/.github/CONTRIBUTING.md)

**Review by MyreMylar — CHANGES_REQUESTED** [review]
Could you move the file from root into the `.github` subdirectory? It is their file format and it would be nice to keep stuff that is for their platform in one place in case we one day have to move hosts again and there is a new set of special files we need to be up to date.

**Comment by MrF1ow** [comment]
> > I totally understand that. Just so you know though I hardly wrote any of it. **It is 98% what was written in the wiki pages.** I just collected it all into one document.
> 
> I think this cuts to the heart of this. I think we should have a CONTRIBUTING.md file, but it should be brief and largely be composed of links to our existing documentation on the Wiki - otherwise we are just duplicating text in two places that we then have to maintain.
> 
> Pygame is older than Github and historically the contribution documentation has been on a wiki like page so I'd like to continue that tradition. I think we can accomodate people who search for a CONTRIBUTING.md file by just linking them to the existing documentation and making any improvements needed over there.
> 
> Does that make sense? I don't want to be updating text in two places as things change.
> 
> Here is an example of another large project (numpy) that takes this approach with CONTRIBUTING.md:
> 
> https://github.com/numpy/numpy/blob/main/.github/CONTRIBUTING.md

This makes sense. I am more than willing to make a new pull request with what you said and making sure it is in `.rst` format.

**Comment by MyreMylar** [comment]
> This makes sense. I am more than willing to make a new pull request with what you said and making sure it is in `.rst` format. Does this sound good to you?

I thought the .md stood for 'markdown'? I'm not sure a .md file cand been in .rst format. If it can, then sure - but the main point is not the style of the formatting in the `CONTRIBUTING.md` file it is to make it much shorter than in this PR and consist mainly of links to the wiki contributing documentation. 

I'm thinking of people who search `pygame-ce CONTRIBUTING.md` or use some other contributing tool to find contribution instructions by looking specifically for this file in GitHub repos. Then I want the file to contain hyperlinks to our existing wiki documentation.

If the documentation on the wiki currently sucks, for whatever reason (something I'm quite willing to believe because I wrote a lot of it!) then I'd like to improve it on the wiki and not have to keep the text in `CONTRIBUTING.md` up to date with the text on the Wiki and visa versa as this is a maintenance burden. The point of it being a "contributor wiki" is that members of the pygame-ce contributors group (a group consisting of people who've contributed to the project a few times) can edit it and hopefully keep it useful, but most of it is not relevant to the end-users.

Ideally Github wikis would also be able to accept pull requests to let everyone recommend changes. Unfortunately GitHub has not made any moves towards this in some time. So far it's not really been too much of an issue just to slap up complaints in issues or on discord and have a pygame-ce contributor (from the community group) just go in and fix it directly. 

Again, if you look at how numpy does it their contribution documentation is also on a separate web page - and the `contributing.md` file is 40 lines with 5 links to pages of more detailed information - I'd like something short like that. 

On a separate note, we could also use linking to the contributor documentation in the wiki, either via the CONTRIBUTING.md file or just directly to the index page on the wiki. There is separately a plan afoot to somewhat rewrite the whole readme file so this part may become superseded by that PR when it materialises.

**Comment by MrF1ow** [comment]
> > This makes sense. I am more than willing to make a new pull request with what you said and making sure it is in `.rst` format. Does this sound good to you?
> 
> 
> 
> I thought the .md stood for 'markdown'? I'm not sure a .md file can be in .rst format. If it can, then sure - but the main point is not the style of the formatting in the `CONTRIBUTING.md` file it is to make it much shorter than in this PR and consist mainly of links to the wiki contributing documentation. 
> 
> 
> 
> I'm thinking of people who search `pygame-ce CONTRIBUTING.md` or use some other contributing tool to find contribution instructions by looking specifically for this file in GitHub repos. Then I want the file to contain hyperlinks to our existing wiki documentation.
> 
> 
> 
> If the documentation on the wiki currently sucks, for whatever reason (something I'm quite willing to believe because I wrote a lot of it!) then I'd like to improve it on the wiki and not have to keep the text in `CONTRIBUTING.md` up to date with the text on the Wiki and visa versa as this is a maintenance burden. The point of it being a "contributor wiki" is that members of the pygame-ce contributors group (a group consisting of people who've contributed to the project a few times) can edit it and hopefully keep it useful, but most of it is not relevant to the end-users.
> 
> 
> 
> Ideally Github wikis would also be able to accept pull requests to let everyone recommend changes. Unfortunately GitHub has not made any moves towards this in some time. So far it's not really been too much of an issue just to slap up complaints in issues or on discord and have a pygame-ce contributor (from the community group) just go in and fix it directly. 
> 
> 
> 
> Again, if you look at how numpy does it their contribution documentation is also on a separate web page - and the `contributing.md` file is 40 lines with 5 links to pages of more detailed information - I'd like something short like that. 
> 
> 
> 
> On a separate note, we could also use linking to the contributor documentation in the wiki, either via the CONTRIBUTING.md file or just directly to the index page on the wiki. There is separately a plan afoot to somewhat rewrite the whole readme file so this part may become superseded by that PR when it materialises.

Yeah the .md does stand for MarkDown, and I get what he was saying about making it shorter and just a place for reference to the wiki pages. Similar to how numpy does it.

I will get something to you guys shortly if that is alright. I got a wedding I got to go to today. Thanks for letting me do this!

**Comment by Starbuck5** [comment]
Call me he who shall not be named, but I don't want another file in the root directory.

I think the clear solution here is just to link the wiki from the existing README.

No duplicated content, no extra files.

Given how difficult (unfortunately) it is to contribute to this library, I don't think "I can't find a contributing.md file so I'm going to give up on my contribution" is a valid concern.

**Comment by MrF1ow** [comment]
Here is a pull request for the addition of just a "How to Contribute" section to the `README.rst` instead of an entire file. @MyreMylar if you want the addition of smaller `Contribution.md` in the `./github/` directory, I am more than happy to do that, but @Starbuck5 was pretty accurate in only needing one small section in the `README.rst` to show users where to go.

Just let me know

**Comment by ankith26** [comment]
I'm personally fine with either approach, and also a possible third approach where we do both.

**Comment by ankith26** [comment]
I have merged your other PR as it was more straightforward than this one

**Comment by Starbuck5** [comment]
Since the other PR has been merged, I'm going to close this one.

**Pull request closed without merging**
