### PR TITLE
Remove and deprecate cythonised sprite module

### LINKED ISSUE #2342: Migrate `pygame.sprite` to C (and/or remove the Cythonized sprite)?
There was an attempt upstream to port `pygame.sprite` to Cython, but that seems to have died. I thought a conversation was had about moving it directly to C, but I can't find any record of it. Should the module be ported to C?

### PR DESCRIPTION
**Pull request by MyreMylar**
fixes #2342 

**Motivation:**
After PR #2533 the normal sprite submodule's Group.draw() call is faster than the current cythonised sprite submodule, having a second cython-version of the sprite submodule is an additional pain to maintain. The general approach we are transitioning towards in pygame-ce is to use the C extension API where it helps with performance and keep other stuff in pure python where we can leverage the performance work of the CPython team - this is going to mean the gradual elimination of the current middle layer that is our Cython code.

Maintenance is the biggest hurdle in keeping most open source projects going and hopefully this is one tiny step in making pygame-ce a little bit easier to mainatain.

### CODE REVIEW

**Comment by MyreMylar** [comment]
This was the performance test code I was using:

```python
import timeit

time_taken = timeit.timeit(
    "draw_sprites(display_surf, test_sprite_group)",
    setup="import pygame\n\n"
    "pygame.init()\n\n"
    "display_surf = pygame.display.set_mode((800, 600))\n\n"
    "test_sprite_group = pygame.sprite.Group()\n\n"
    "for i in range(300):\n"
    "   test_sprite = pygame.sprite.Sprite(test_sprite_group)\n"
    "   test_sprite.image = pygame.Surface((64,64))\n"
    "   test_sprite.image.fill('red')\n"
    "   test_sprite.rect = pygame.Rect((i*2,i*2), (64, 64))\n"
    "def draw_sprites(display_surface, sprite_group):\n"
    "    display_surface.fill((255, 255, 255))\n"
    "    sprite_group.draw(display_surface)\n"
    "    pygame.display.flip()\n",
    number=1000,
)
print("time taken to do 1000 warm-up sprite draws (don't count these as perf takes a while to warm up)", time_taken)


time_taken = timeit.timeit(
    "draw_sprites(display_surf, test_sprite_group)",
    setup="import pygame\n"
    "import pygame._sprite\n\n"
    "pygame.init()\n\n"
    "display_surf = pygame.display.set_mode((800, 600))\n\n"
    "test_sprite_group = pygame._sprite.Group()\n\n"
    "for i in range(300):\n"
    "   test_sprite = pygame._sprite.Sprite(test_sprite_group)\n"
    "   test_sprite.image = pygame.Surface((64,64))\n"
    "   test_sprite.image.fill('red')\n"
    "   test_sprite.rect = pygame.Rect((i*2,i*2), (64, 64))\n"
    "def draw_sprites(display_surface, sprite_group):\n"
    "    display_surface.fill((255, 255, 255))\n"
    "    sprite_group.draw(display_surface)\n"
    "    pygame.display.flip()\n",
    number=1000,
)
print("time taken to do 1000 cython sprite draws", time_taken)

time_taken = timeit.timeit(
    "draw_sprites(display_surf, test_sprite_group)",
    setup="import pygame\n\n"
    "pygame.init()\n\n"
    "display_surf = pygame.display.set_mode((800, 600))\n\n"
    "test_sprite_group = pygame.sprite.Group()\n\n"
    "for i in range(300):\n"
    "   test_sprite = pygame.sprite.Sprite(test_sprite_group)\n"
    "   test_sprite.image = pygame.Surface((64,64))\n"
    "   test_sprite.image.fill('red')\n"
    "   test_sprite.rect = pygame.Rect((i*2,i*2), (64, 64))\n"
    "def draw_sprites(display_surface, sprite_group):\n"
    "    display_surface.fill((255, 255, 255))\n"
    "    sprite_group.draw(display_surface)\n"
    "    pygame.display.flip()\n",
    number=1000,
)
print("time taken to do 1000 sprite draws", time_taken)
```

On current main the cython sprite module outperforms the normal sprite module in drawing, but when I try it with the newly optimised sprite module in #2533 the normal sprite is now better than cython sprite.

**Review by dr0id — APPROVED** [review]

**Review by Starbuck5 — APPROVED** [review]
I'm good to see this removed, I like that you've justified this with performance and maintainability, and I concur.

**Comment by Starbuck5** [comment]
Another bonus of this is that it makes the installed wheel smaller since it doesn't have the _sprite object. For me it's a 300kb difference.

**Review by ankith26 — APPROVED** [review]
LGTM, thanks for the PR! Seeing 44k lines being removed is always a nice feeling

**Pull request merged**
