### PR TITLE
Fix cppcheck crash.

### PR DESCRIPTION
**Pull request by yunline**
Fix error in step `Install deps`.

### CODE REVIEW

**Review by oddbookworm — APPROVED** [review]
I'm not sure about this being a permanent solution because I'm not entirely sure if updating this is ultimately needed for the CI or if the docker images are just having a stroke, but the Ubuntu 20.04 check passed and I'm fairly confident that it resolves the issue with the cppcheck workflow as well because they complain about the same thing. So I'm approving it on the basis that this will at least get us back on track for getting PR's to pass the checks.

**Comment by ankith26** [comment]
Hmmm. This fix works for now, but I suspect this fix would not be needed once the issue is fixed on the github actions side

**Comment by MyreMylar** [comment]
I reported the underlying issue to GitHub here: https://github.com/orgs/community/discussions/47863

We could just merge this for now and monitor that issue to see if they take action to fix it?

**Review by Starbuck5 — APPROVED** [review]
I say we merge this for now.

**Pull request merged**
