### PR TITLE
Revert 3140 draw.aaline width

### PR DESCRIPTION
**Pull request by ankith26**
Reverts pygame-community/pygame-ce#3140 completely. #3182 is doing a partial revert already but I believe a full revert is safer in this case, especially given the author of the original PR has come up with an entirely new implementation

### CODE REVIEW

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Comment by oddbookworm** [comment]
I'm curious why only the circleci runs ran here

**Review by oddbookworm — APPROVED** [review]
LGTM! Although, I'm not merging quite yet until I understand why not all actions ran here

**Comment by ankith26** [comment]
github CI is only configured to run on pushes and PRs made against the `main` branch. The CI is going to do a run during the release as well, so if there is any issue we can still catch it then

**Comment by oddbookworm** [comment]
🤦‍♂️ yep, I should have paid attention to what branch it was going to

**Pull request merged**
