### PR TITLE
Further deprecation of deprecated sprite groups

### PR DESCRIPTION
**Pull request by Matiiss**
Follow through of https://github.com/pygame-community/pygame-ce/pull/2036

### CODE REVIEW

**Comment by Starbuck5** [comment]
These things were always minor, but this is still a compatibility break. I don't think they should be removed.

Updating docs and tutorials to not mention them is fine, seems like a good idea.

**Comment by Matiiss** [comment]
> These things were always minor, but this is still a compatibility break. I don't think they should be removed.
> 
> Updating docs and tutorials to not mention them is fine, seems like a good idea.

I was just following the contents of the deprecation warnings, which were put there by MyreMylar. Also, I don't see that much harm in removing these particular groups, since they're just aliases, those few few people who actually use them and at some later point move over to pygame-ce can just do a find and replace and change the names to `Group` or that other group.

**Comment by Starbuck5** [comment]
> I was just following the contents of the deprecation warnings, which were put there by MyreMylar

I didn't notice the deprecation warnings said that. That should be changed.

> those few few people who actually use them and at some later point move over to pygame-ce can just do a find and replace and change the names to Group or that other group

When you recommend someone switches over to pygame-ce, don't you want to be able say "it won't break your code" with a clean conscience?

**Comment by Matiiss** [comment]
Alright, added back the functional bits to maintain compatibility and changed deprecation warnings to just inform users that the features will be removed in a future version.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Review by Starbuck5 — APPROVED** [review]
Changes make sense, thanks for the PR.

**Pull request merged**
