### PR TITLE
Removed appveyor badge from the Readme file

### PR DESCRIPTION
**Pull request by Ritikkhulbe**
Issue - https://github.com/pygame-community/pygame-ce/issues/1892

I have removed the Appveyor badge from the Readme file as the project is not using it for windows build

### CODE REVIEW

**Comment by oddbookworm** [comment]
9C59F779-86A7-4F48-84F5-8E87030B64EF

This needs to be removed too

**Comment by Ritikkhulbe** [comment]
@oddbookworm yes on it , i missed it

**Review by oddbookworm — CHANGES_REQUESTED** [review]
Reviewing on mobile is a pain, but you should fix what I commented on above. Look at the top of the file

**Comment by Ritikkhulbe** [comment]
I have made the changes and pushed on to my local forked project

**Comment by Ritikkhulbe** [comment]
@oddbookworm sorry for the mistake, im getting around github for the first time , and this is my second contribution on the web

**Review by oddbookworm — APPROVED** [review]
LGTM! Thanks for submitting your first PR 🎉

**Comment by oddbookworm** [comment]
> @oddbookworm sorry for the mistake, im getting around github for the first time , and this is my second contribution on the web

Hey, it’s all good. We all gotta start somewhere after all. That’s why I didn’t just fix that small issue myself. Good way for someone to get their feet wet

**Comment by Ritikkhulbe** [comment]
> > @oddbookworm sorry for the mistake, im getting around github for the first time , and this is my second contribution on the web
> 
> Hey, it’s all good. We all gotta start somewhere after all. That’s why I didn’t just fix that small issue myself. Good way for someone to get their feet wet. Although, pinging me for every message is a bit excessive 😅
hehe thank you, i will be doing a lot of contributions from now on

**Comment by Ritikkhulbe** [comment]
> > @oddbookworm sorry for the mistake, im getting around github for the first time , and this is my second contribution on the web
> 
> Hey, it’s all good. We all gotta start somewhere after all. That’s why I didn’t just fix that small issue myself. Good way for someone to get their feet wet. Although, pinging me for every message is a bit excessive 😅

Hehe thank you, i will be doing a lot of contributions from now on

**Review by ankith26 — APPROVED** [review]
Thanks for contributing! :+1:

**Pull request merged**
