### PR TITLE
Documentation retarget

### PR DESCRIPTION
**Pull request by novialriptide**
fixes: https://github.com/pygame-community/pygame-ce/issues/1864

### CODE REVIEW

**Comment by yunline** [comment]
image
Also in README.rst

**Review by yunline — COMMENTED** [review]
Also in README.rst and setup.py
image
image

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Comment by MyreMylar** [comment]
> Also in README.rst and setup.py image image

I think we'll handle these in a new PR. Need to actually make the compilation wiki pages for linux and mac.

**Review by Starbuck5 — APPROVED** [review]

**Pull request merged**
