### PR TITLE
Fix stubcheck error on windows, mark typealiases as such in typing

### PR DESCRIPTION
**Pull request by zoldalma999**

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM, thanks :tada:

**Review by bilhox — APPROVED** [review]
LGTM !

**Review by damusss — APPROVED** [review]
Sure, LGTM 👍

**Comment by aatle** [comment]
Note: (despite the 3 approving reviews and the passed checks,) the `TypeAlias` additions are actually problematic because it is unavailable for python <3.10.
See #3149 for the fix.

**Pull request merged**
