### PR TITLE
Use `SDL_GetTicks64` instead of `SDL_GetTicks`

### PR DESCRIPTION
**Pull request by avaxar**
Supposed to close pygame/pygame#3658. This replaces the every of `SDL_GetTicks` with `SDL_GetTicks64`. `SDL_GetTicks` would overflow once every 49.71 days, as it returns an `Uint32`. Of course, most programs wouldn't run that long, but it's still nice to fix such case for the few running it that long. Using `SDL_GetTicks64` returns an `Uint64`, which extends the overflowing cycle to 584,542,046 years. If anyone's planning to make a graphical time-capsule using pygame to the end of Earth, hit me up to replace it with `SDL_GetTicks128`.

### CODE REVIEW

**Comment by Starbuck5** [comment]
https://wiki.libsdl.org/SDL2/SDL_GetTicks64

> This function is available since SDL 2.0.18.

**Comment by avaxar** [comment]
Ah, thought it was from 2.0.8.

**Comment by Starbuck5** [comment]
You could add a PG_GetTicks64 that either calls SDL_GetTicks or SDL_GetTicks64 and returns a 64 bit int either way.

pgcompat.c or one of the pygame.h's would be a good location.

**Comment by avaxar** [comment]
Alright. No wonder the CIs failed. Their SDL versions were less than 2.0.18.

**Review by Matiiss — APPROVED** [review]
LGTM

**Review by MyreMylar — APPROVED** [review]
I think at some point we'll just want to upgrade to using `SDL_GetPerformanceCounter()` on modern systems as in Ankith's old timing PR. 

AFAIK it is just superior in every way.

Still this should help people who run pygame-ce apps for months at a time. Which is probably someone!

**Comment by robertpfeiffer** [comment]
> Still this should help people who run pygame-ce apps for months at a time. Which is probably someone!

:wave:

**Pull request merged**
