### PR TITLE
Fix editable install test fixtures logic

### PR DESCRIPTION
**Pull request by ankith26**
Simple PR to fix a small issue in our test runner script. With editable installs, the older path resolution logic didn't give correct paths anymore, resulting in a fail (issue discovered while working on #2990)

### CODE REVIEW

**Review by oddbookworm — COMMENTED** [review]
It would be nice to see a CI run that demonstrates that these changes do, in fact, solve the problem you've set out to solve here. Since none of our current CI uses editable installs to the best of my knowledge, maybe that would come with a modification to an existing build or a new build? Or maybe passing CI in #2990 after pulling in these changes?

**Comment by ankith26** [comment]
My intention is to merge this PR and then rebase #2990 to get this fix

**Review by oddbookworm — APPROVED** [review]
LGTM

**Review by zoldalma999 — APPROVED** [review]
Tested locally, works. Thanks for the PR!

**Pull request merged**
