### PR TITLE
Remove video.Renderer.blit()

### PR DESCRIPTION
**Pull request by yunline**
image

### CODE REVIEW

**Review by MyreMylar — APPROVED** [review]
I agree that it makes little sense for us to try and pretend that the GPU Renderer/Texture API from SDL is the same as the CPU blit API. 

I think instead we should focus our compatibility efforts on where we can port from one API to the other (e.g. nicely turning a surface into a Texture). Also, moving all this stuff into C.

I guess we could deprecation warning this, but I'm inclined not to while the whole module is marked experimental.

**Comment by yunline** [comment]
Replace 'Renderer.blit()' with 'Renderer.draw_texture()' and remove the 'Texture.draw()' may be better.

Texture should be a class that 'storage texture data'. Drawing is handled by Renderer. 'Renderer.draw_texture()' would be more intuitive.

**Comment by yunline** [comment]
I also recommend to add a 'target' parameter to all drawing functions of rendeter to draw graphics on a texture.

**Comment by yunline** [comment]
This PR is not good enough.

**Pull request closed without merging**
