### PR TITLE
Deprecate `setup.py docs`, make docs in meson build

### PR DESCRIPTION
**Pull request by ankith26**
This is another small step in our move away from `setup.py`.

`python setup.py docs` internally executes `python buildconfig/makeref.py`, so this PR makes the straightforward replacement.

Also, another change that this PR makes is that it adds an invocation of above into the meson build itself. This makes the build process further streamlined under one command.

Should also help fix the fails in #2850

### CODE REVIEW

**Comment by MyreMylar** [comment]
Should we take the opportunity to rename 'makeref.py' if it is going to be user facing? That is kind of a terrible name for a 'build the docs' script file.

**Comment by ankith26** [comment]
How about just renaming it to just `docs.py`? or `make_docs.py`?

**Review by MyreMylar — APPROVED** [review]
OK, that works for me 👍

**Review by zoldalma999 — APPROVED** [review]
Looks good to me, nice to see progress on moving away from setup.py

**Pull request merged**
